# Generated by Django 6.1.1 on 2026-09-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='organizations', to='gh_permissions.account')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='gh_permissions.organization')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
                'unique_together': {('organization', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='gh_permissions.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='gh_permissions.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountRepoGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_grants', to='gh_permissions.account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_grants', to='gh_permissions.operation')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_grants', to='gh_permissions.repository')),
            ],
            options={
                'unique_together': {('account', 'repository', 'operation')},
            },
        ),
        migrations.CreateModel(
            name='PermissionBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('operations', models.ManyToManyField(blank=True, related_name='bundles', to='gh_permissions.operation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_bundles', to='gh_permissions.team')),
            ],
            options={
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamRepoGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_grants', to='gh_permissions.operation')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_grants', to='gh_permissions.repository')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_grants', to='gh_permissions.team')),
            ],
            options={
                'unique_together': {('team', 'repository', 'operation')},
            },
        ),
    ]
