# Generated by Django 6.1.1 on 2026-10-04 03:52
#
# Unpublished 0.1.0.dev0 reset. 0001_initial stays as published history.
# This migration does not map Operation rows onto auth.Permission.
#
# Before either operation foreign key is retargeted, every
# UserRepositoryPermission and TeamRepositoryPermission row is deleted.
# Removing and re-adding Team.allowed_operations drops the ceiling
# through-table. Old operation_id values are not copied, so an integer
# that happens to equal an auth_permission.id cannot become a different
# grant. The loss is irreversible: migrating backwards raises
# IrreversibleError and does not restore those rows.

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def delete_legacy_operation_grants(apps, schema_editor):
    """Delete Operation-backed grants. Do not reuse their primary keys."""
    alias = schema_editor.connection.alias
    direct = apps.get_model('gh_permissions', 'UserRepositoryPermission')
    team = apps.get_model('gh_permissions', 'TeamRepositoryPermission')
    direct.objects.using(alias).all().delete()
    team.objects.using(alias).all().delete()


def reverse_delete_legacy_operation_grants(apps, schema_editor):
    raise IrreversibleError(
        '0002_auth_permission_terminal deleted UserRepositoryPermission '
        'and TeamRepositoryPermission rows and the team ceiling. Those '
        'Operation-backed grants are not restored.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='allowed_operations',
        ),
        migrations.RunPython(
            delete_legacy_operation_grants,
            reverse_delete_legacy_operation_grants,
        ),
        migrations.AlterField(
            model_name='userrepositorypermission',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_repository_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='teamrepositorypermission',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_repository_permissions', to='auth.permission'),
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': (('read_repository', 'Can read repository'), ('write_repository', 'Can write repository'), ('admin_repository', 'Can administer repository')), 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='team',
            name='allowed_operations',
            field=models.ManyToManyField(blank=True, related_name='allowed_teams', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
