# Generated by Django 6.1.1 on 2026-10-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOwnerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner_grants', to='gh_permissions.operation')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_grant', to='gh_permissions.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
