# Generated by Django 6.1.1 on 2026-10-04 03:52
#
# Forward schema change on the unreleased 0.1.0.dev0 line. 0001_initial
# stays as published history. The operation foreign keys are retargeted
# at auth.Permission. The team ceiling M2M cannot change its target in
# place, so Django removes and re-adds that field. Existing Operation
# primary keys are not remapped onto Permission rows; a database that
# already stored Operation grants has to be rebuilt.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='allowed_operations',
        ),
        migrations.AlterField(
            model_name='userrepositorypermission',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_repository_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='teamrepositorypermission',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_repository_permissions', to='auth.permission'),
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'permissions': (('read_repository', 'Can read repository'), ('write_repository', 'Can write repository'), ('admin_repository', 'Can administer repository')), 'verbose_name': 'repository', 'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='team',
            name='allowed_operations',
            field=models.ManyToManyField(blank=True, related_name='allowed_teams', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
