# Generated by Django 6.1.1 on 2026-10-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0002_auth_permission_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('manage_organization', 'Can manage organization'),)},
        ),
        migrations.CreateModel(
            name='OrganizationOwnerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner_grants', to='auth.permission')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_grant', to='gh_permissions.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
