# Generated by Django 6.1.1 on 2026-10-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_shared_owner_group(apps, schema_editor):
    """Point existing organizations at one group and reserve their names.

    Permission rows are not assigned here. ``post_migrate`` seeds those
    after ``auth`` creates them. Historical users are left alone: this
    example did not previously share their names with organizations.
    """
    alias = schema_editor.connection.alias
    Group = apps.get_model('auth', 'Group')
    Organization = apps.get_model('gh_permissions', 'Organization')
    Alias = apps.get_model('gh_permissions', 'Alias')
    group, _created = Group.objects.using(alias).get_or_create(
        name='organization-owners',
    )
    for organization in Organization.objects.using(alias).iterator():
        if organization.name:
            Alias.objects.using(alias).get_or_create(name=organization.name)
        if organization.owner_group_id != group.pk:
            organization.owner_group_id = group.pk
            organization.save(update_fields=['owner_group'])


def clear_shared_owner_group(apps, schema_editor):
    alias = schema_editor.connection.alias
    Organization = apps.get_model('gh_permissions', 'Organization')
    Alias = apps.get_model('gh_permissions', 'Alias')
    for organization in Organization.objects.using(alias).iterator():
        if organization.name:
            Alias.objects.using(alias).filter(name=organization.name).delete()
        organization.owner_group_id = None
        organization.save(update_fields=['owner_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0003_organization_owner_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationownerpermission',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='organizationownerpermission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationownerpermission',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='userrepositorypermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrepositorypermission',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='userrepositorypermission',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='userrepositorypermission',
            name='user',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_organizations', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organization',
            name='personal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(
            assign_shared_owner_group,
            clear_shared_owner_group,
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_organizations', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name__isnull', False), ('personal_user__isnull', True), models.Q(('name', ''), _negated=True)), models.Q(('name__isnull', True), ('personal_user__isnull', False)), _connector='OR'), name='organization_personal_or_conventional'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_repository_name_per_organization'),
        ),
        migrations.AddField(
            model_name='organizationownership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='gh_permissions.organization'),
        ),
        migrations.AddField(
            model_name='organizationownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_organizations', through='gh_permissions.OrganizationOwnership', through_fields=('organization', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repositorycollaborator',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='repository_collaborators', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='repositorycollaborator',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='gh_permissions.repository'),
        ),
        migrations.AddField(
            model_name='repositorycollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrganizationOwnerPermission',
        ),
        migrations.DeleteModel(
            name='UserRepositoryPermission',
        ),
        migrations.AddConstraint(
            model_name='organizationownership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_organization_ownership'),
        ),
        migrations.AddConstraint(
            model_name='repositorycollaborator',
            constraint=models.UniqueConstraint(fields=('user', 'repository'), name='unique_repository_collaborator'),
        ),
    ]
