# Generated by Django 6.1.2 on 2026-10-10 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0004_shared_names_ownership_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_permissions', models.ManyToManyField(blank=True, related_name='repository_delegations', to='auth.permission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_repository_delegations', to=settings.AUTH_USER_MODEL)),
                ('approved_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_repository_delegations', to='gh_permissions.organization')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_repository_delegations', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='gh_permissions.repository')),
                ('sponsor_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_delegations', to='gh_permissions.organizationownership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delegate', 'sponsor_ownership', 'repository'), name='unique_repository_delegation')],
            },
        ),
    ]
