# Generated by Django 6.1.2 on 2026-10-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gh_permissions', '0005_repositorydelegation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPersonalRepositoriesDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_permissions', models.ManyToManyField(blank=True, related_name='all_personal_repositories_delegations', to='auth.permission')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_all_personal_repositories_delegations', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_all_personal_repositories_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delegate', 'sponsor'), name='unique_all_personal_repositories_delegation')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRepositoryDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_permissions', models.ManyToManyField(blank=True, related_name='personal_repository_delegations', to='auth.permission')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_personal_repository_delegations', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_delegations', to='gh_permissions.repository')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_personal_repository_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delegate', 'sponsor', 'repository'), name='unique_personal_repository_delegation')],
            },
        ),
    ]
